# myapp/k8s/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort    # good for minikube / local testing
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
