name: Docker CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull Docker image
        run: docker pull devparmar1676/myapp:local-test
