name: Docker CI

on:
  push:
    branches: [ main ]  # Trigger on push to main branch
  workflow_dispatch:      # Allows manual trigger

jobs:
  build-and-pull:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Pull the private Docker image
      - name: Pull Docker image
        run: docker pull devparmar1676/myapp:local-test
